# Generated by Django 4.0.2 on 2022-02-09 18:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_usd', models.IntegerField(blank=True, null=True)),
                ('business_usd', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ActorsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('spouse', models.CharField(blank=True, max_length=100, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='children', to='core.Children')),
                ('movies', models.ManyToManyField(blank=True, related_name='movies', to='core.Movies')),
                ('pictures', models.ManyToManyField(blank=True, related_name='pictures', to='core.Pictures')),
            ],
        ),
    ]
